# Generated by Django 5.1 on 2024-10-09 16:02

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_posts_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=30, unique=True, verbose_name='name'),
        ),
    ]
